/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'mati' at '26/01/17 9:39' with Gradle 3.0
 *
 * @author mati, @date 26/01/17 9:39
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
