
// This file has been generated by the GUI designer. Do not modify.
namespace PArticulo
{
	public partial class DBCommandHelper
	{
		public virtual void Build ()
		{
			// Action group PArticulo.DBCommandHelper
		}
	}
}
